query postsAll(
	$page: Int!
	$first: Int!
	$where: AllPostsWhereWhereConditions
	$order: [OrderByClause!]
) {
	allPosts(first: $first, page: $page, where: $where, order: $order) {
		data {
			id
			title
			comments_count
		}
		paginatorInfo {
			count
			currentPage
			firstItem
			hasMorePages
			lastItem
			lastPage
			perPage
			total
		}
	}
}
